### ISSUE TITLE
Searching with special characters (brackets etc.)

### ISSUE THREAD

**Issue by Rosnicka** [Kcko/aw-select#1]
If you use brackets in search dialog, nothing happen.

![search_issue](https://cloud.githubusercontent.com/assets/13046097/10242192/64dfb9d6-68ef-11e5-9c72-bbc71dbe4cf4.png)

**Comment by Kcko** [comment]
Thx for report, i will fix it.

**Comment by Kcko** [comment]
Fixed via 7436bc6e1178692e813a1b6785e7138037713305
